---
apiVersion: v1
kind: Service
metadata:
  name: ordermicroservice-service
spec:
  selector:
    app: ordermicroservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
